version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    env_file:
      - ".env"
    volumes:
      - .sql:/docker-entrypoint-initdb.d/sql/SCRIPT_BASE_DE_DATOS.sql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
