

CREATE TABLE PRODUCTOS (
                    EAN INTEGER AUTO_INCREMENT PRIMARY KEY,
                    NOMBRE VARCHAR(50),
                    MARCA VARCHAR(25),
                    PRECIO DECIMAL(5,2),
                    ALTURA DECIMAL(5,2),  
                    ANCHURA DECIMAL(5,2),
                    PESO DECIMAL(5,2),
                    NUM_ELEMENTOS INTEGER,
                    DESCRIPCION VARCHAR(100));

CREATE TABLE EMPLEADOS (
                    ID_EMPLEADO INTEGER AUTO_INCREMENT PRIMARY KEY,
                    NOMBRE VARCHAR(25) ,
                    APELLIDOS VARCHAR(25),
                    SALARIO INTEGER,
                    CATEGORIA VARCHAR(25),
                    CHECK (CATEGORIA IN ('Reponedor', 'Cajero', 'Empleado', 'Encargado')));

CREATE TABLE CLIENTE (
                    ID_CLIENTE INTEGER AUTO_INCREMENT PRIMARY KEY,
                    NOMBRE VARCHAR(25) ,
                    APELLIDOS VARCHAR(25),
                    COD_POSTAL INTEGER);

CREATE TABLE SEDE (
                    UBICACION VARCHAR(25) PRIMARY KEY);

CREATE TABLE COMPRA (
                    ID_COMPRA INTEGER AUTO_INCREMENT,
                    FECHA_COMPRA VARCHAR(25),
                    ID_CLIENTE INTEGER ,
                    PRIMARY KEY (ID_COMPRA),
                    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE));



CREATE TABLE COMPRA_PRODUCTO (
                    EAN INTEGER,
                    ID_COMPRA INTEGER,
                    CANTIDAD INTEGER,
                    PRIMARY KEY (EAN, ID_COMPRA),
                    FOREIGN KEY (EAN) REFERENCES PRODUCTOS(EAN),
                    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA));
                    
CREATE TABLE PRODUCTO_SEDE (
                    EAN INTEGER,
                    UBICACION VARCHAR(25),
                    STOCK INTEGER,
                    PRIMARY KEY (EAN, UBICACION),
                    FOREIGN KEY (EAN) REFERENCES PRODUCTOS(EAN),
                    FOREIGN KEY (UBICACION) REFERENCES SEDE(UBICACION));

-- CREACION DE LAS VISTAS

--! COMPRAS POR CÓDIGO POSTAL
CREATE OR REPLACE VIEW COMPRAS_POR_CODIGO_POSTAL AS
SELECT COD_POSTAL, COUNT(ID_COMPRA) AS NUM_COMPRAS
FROM CLIENTE
JOIN COMPRA ON CLIENTE.ID_CLIENTE = COMPRA.ID_CLIENTE
GROUP BY COD_POSTAL;

--! STOCK DE PRODUCTOS
CREATE OR REPLACE VIEW STOCK_PRODUCTOS AS
SELECT P.NOMBRE, PS.STOCK
FROM PRODUCTOS P
JOIN PRODUCTO_SEDE PS ON P.EAN = PS.EAN;

CREATE OR REPLACE VIEW VISTA_PRODUCTOS AS
SELECT EAN, NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION
FROM PRODUCTOS;

CREATE OR REPLACE VIEW VISTA_EMPLEADOS AS
SELECT ID_EMPLEADO, NOMBRE, APELLIDOS, SALARIO, CATEGORIA
FROM EMPLEADOS;

CREATE OR REPLACE VIEW VISTA_CLIENTES AS
SELECT ID_CLIENTE, NOMBRE, APELLIDOS, COD_POSTAL
FROM CLIENTE;

CREATE OR REPLACE VIEW VISTA_COMPRA_PRODUCTOS AS
SELECT EAN, ID_COMPRA, CANTIDAD
FROM COMPRA_PRODUCTO;

CREATE OR REPLACE VIEW VISTA_SEDE AS
SELECT UBICACION
FROM SEDE;

CREATE OR REPLACE VIEW VISTA_COMPRA AS
SELECT ID_COMPRA, FECHA_COMPRA, ID_CLIENTE
FROM COMPRA;

CREATE OR REPLACE VIEW VISTA_PRODUCTO_SEDE AS
SELECT EAN, UBICACION, STOCK
FROM PRODUCTO_SEDE;


-- INSERT A LAS TABLAS.
INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Juan', 'Gómez', 2000.00, 'Reponedor');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('María', 'López', 2200.00, 'Reponedor');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Pedro', 'Martínez', 2500.00, 'Empleado');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Ana', 'Sánchez', 1900.00, 'Encargado');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Miguel', 'González', 2300.00, 'Reponedor');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Laura', 'Rodríguez', 2100.00, 'Cajero');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('David', 'Fernández', 2400.00, 'Empleado');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Sara', 'Pérez', 2000.00, 'Empleado');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Carlos', 'Ruiz', 2200.00, 'Reponedor');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Elena', 'Gómez', 2300.00, 'Reponedor');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Pablo', 'Hernández', 2400.00, 'Cajero');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Carmen', 'Díaz', 2000.00, 'Reponedor');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('José', 'Moreno', 2200.00, 'Empleado');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Paula', 'Muñoz', 2100.00, 'Reponedor');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Manuel', 'Jiménez', 2500.00, 'Encargado');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Isabel', 'Álvarez', 2300.00, 'Encargado');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Raúl', 'Romero', 2400.00, 'Reponedor');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Eva', 'Torres', 2000.00, 'Cajero');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Javier', 'Giménez', 2200.00, 'Empleado');

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SALARIO, CATEGORIA) 
VALUES ('Nuria', 'Navarro', 2100.00, 'Cajero');



INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Juan', 'García', 28001);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('María', 'López', 28002);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Pedro', 'Martínez', 28003);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Ana', 'Sánchez', 28004);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Miguel', 'González', 28005);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Laura', 'Rodríguez', 28006);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('David', 'Fernández', 28007);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Sara', 'Pérez', 28008);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Carlos', 'Ruiz', 28009);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Elena', 'Gómez', 28010);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Pablo', 'Hernández', 28011);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Carmen', 'Díaz', 28012);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('José', 'Moreno', 28013);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Paula', 'Muñoz', 28014);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Manuel', 'Jiménez', 28015);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Isabel', 'Álvarez', 28016);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Raúl', 'Romero', 28017);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Eva', 'Torres', 28018);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Javier', 'Giménez', 28019);

INSERT INTO CLIENTE (NOMBRE, APELLIDOS, COD_POSTAL) 
VALUES ('Nuria', 'Navarro', 28020);



INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Leche entera', 'Pascual', 1.20, 20, 10, 1, 50, 'Leche entera pasteurizada en envase de cartón de 1 litro');

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Pan de molde integral', 'Bimbo', 1.50, 15, 10, 0.5, 20, 'Pan de molde integral envasado, ideal para sandwiches');

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Arroz blanco', 'SOS', 0.90, 25, 15, 1, 30, 'Arroz de grano largo para guarniciones y platos principales');

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Pasta italiana', 'Barilla', 1.20, 20, 15, 0.5, 25, 'Pasta italiana tipo espagueti, hecha de sémola de trigo');

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Aceite de oliva virgen extra', 'Carbonell', 3.50, 25, 8, 1, 40, 'Aceite de oliva virgen extra de primera calidad');

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Atún en conserva', 'Calvo', 2.00, 10, 5, 0.2, 60, 'Atún en conserva en aceite vegetal, lata de 80 gramos');

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Huevos de gallina', 'Campofrío', 2.50, 8, 6, 0.3, 12, 'Docena de huevos de gallina frescos, categoría A');

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Tomate pera', 'Cocinero', 1.80, 10, 5, 0.2, 15, 'Tomate pera fresco y jugoso, ideal para ensaladas');

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Queso manchego', 'La Casota', 5.00, 10, 15, 0.4, 8, 'Queso manchego semicurado, elaborado con leche de oveja');

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Cerveza rubia', 'Estrella Galicia', 1.20, 20, 7, 0.5, 24, 'Cerveza rubia tipo Lager, botella de 33 cl');

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Papel higiénico', 'Scottex', 2.50, 25, 20, 1, 16, 'Rollo de papel higiénico de doble capa, paquete de 12 unidades');

INSERT INTO PRODUCTOS (NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION) 
VALUES ('Detergente líquido', 'Ariel', 4.00, 30, 15, 1.5, 10, 'Detergente líquido para lavadora, formato de 3 litros');

INSERT INTO SEDE (UBICACION) VALUES ('Madrid');

INSERT INTO PRODUCTO_SEDE (EAN, UBICACION, STOCK) VALUES (1, 'Madrid', 96);
INSERT INTO PRODUCTO_SEDE (EAN, UBICACION, STOCK) VALUES (2, 'Madrid', 40);
INSERT INTO PRODUCTO_SEDE (EAN, UBICACION, STOCK) VALUES (3, 'Madrid', 60);
INSERT INTO PRODUCTO_SEDE (EAN, UBICACION, STOCK) VALUES (4, 'Madrid', 50);
INSERT INTO PRODUCTO_SEDE (EAN, UBICACION, STOCK) VALUES (5, 'Madrid', 80);
INSERT INTO PRODUCTO_SEDE (EAN, UBICACION, STOCK) VALUES (6, 'Madrid', 72);
INSERT INTO PRODUCTO_SEDE (EAN, UBICACION, STOCK) VALUES (7, 'Madrid', 36);
INSERT INTO PRODUCTO_SEDE (EAN, UBICACION, STOCK) VALUES (8, 'Madrid', 45);

INSERT INTO COMPRA (FECHA_COMPRA, ID_CLIENTE) VALUES (SYSDATE(), 1);
INSERT INTO COMPRA (FECHA_COMPRA, ID_CLIENTE) VALUES (SYSDATE(), 2);
INSERT INTO COMPRA (FECHA_COMPRA, ID_CLIENTE) VALUES (SYSDATE(), 3);
INSERT INTO COMPRA (FECHA_COMPRA, ID_CLIENTE) VALUES (SYSDATE(), 4);
INSERT INTO COMPRA (FECHA_COMPRA, ID_CLIENTE) VALUES (SYSDATE(), 5);
INSERT INTO COMPRA (FECHA_COMPRA, ID_CLIENTE) VALUES (SYSDATE(), 6);
INSERT INTO COMPRA (FECHA_COMPRA, ID_CLIENTE) VALUES (SYSDATE(), 7);
INSERT INTO COMPRA (FECHA_COMPRA, ID_CLIENTE) VALUES (SYSDATE(), 8);