@startuml Diagrama clases Model
' left to right direction
set namespaceSeparator none
allow_mixing

package es.tiernoparla.daw.mercadaw.model {

    package enum{

        enum CategoriaProducto {
            ALIMENTACION
            DROGUERIA
            COSMETICA
        }

        enum CategoriaEmpleado {
            EMPLEADO
            REPONEDOR
            CAJERO
            ENCARGADO
        }
    }

    interface MercaDaw {
        +darAlta(producto: Producto): int
        +darAlta(empleado: Empleado): int
        +visualizarProductos(producto: Producto): void
        +visualizarEmpleados(List<Empleado> empleados): void
        +obtenerPrecio(producto: Producto): double
        +calcularNominas(List<Empleado> empleados): double
        +obtenerPrecioVenta(producto: Producto): String
        +imprimirEtiqueta(producto: Producto): String
    }

    class Sede {

    }

    package entity {
        component Producto <<Java>>
        component Empleado <<Java>>

    }

    Sede o-- Producto
    Sede o-- Empleado

    MercaDaw <|.. Sede

    package dao {
        interface MercaDawDAO {
            +crearTablaProductos(): void
            +crearTablaEmpleados(): void
            +crearTablaCompras(): void
            +insertar(producto: Producto): int
            +insertar(List<Producto> productos): int
            +actualizar(producto: Producto): int
            +borrar(producto: Producto): int
            +insertar(empleado: Empleado): int
            +insertar(List<Empleado> empleados): int
            +actualizar(empleado: Empleado): int
            +borrar(empleado: Empleado): int
        }

        class MercaDawMariaDBDAOImp {
            -conexion: Connection
            -conectar(): Connection
        }

        class MercaDawMockDAOImp

        class MercaDawDAOFactory {
            +{static}obtenerDAO(tipo: TipoDAO): MercaDawDAO
        }

        enum Database {
            MOCK
            MARIADB
        }

        MercaDawDAO <|.. MercaDawMariaDBDAOImp
        MercaDawDAO <|.. MercaDawMockDAOImp

    }
}

component MariaDB <<Database>>
component org.mariadb.jdbc <<JDBC Driver>>

MercaDawMariaDBDAOImp ..> MariaDB
MercaDawMariaDBDAOImp ..> org.mariadb.jdbc

Sede ..> MercaDawDAO

@enduml