@startuml Diagrama clases
set namespaceSeparator none
allow_mixing

package es.tiernoparla.daw.mercadaw.util {
    package reader {
        interface Lector {
            +leerProducto(cadena: String): List<Producto>
            +leerEmpleado(cadena: String): List<Empleado>
        }

        abstract LectorImp {
            #comprobar(codigo: String): void
            #cargar(file: File): String
        }

        class LectorMock
        class LectorCSV {
            +procesarProducto(fila: String): Producto
            +procesarEmpleado(fila: String): Empleado
        }
        class LectorJSON {
            +procesarValor(pareja: String): String
            +procesarProducto(fila: String): Producto
            +procesarEmpleado(fila: String): Empleado
        }
        class LectorXML

        Lector <|.. LectorMock
        Lector <|.. LectorImp

        LectorImp <|-- LectorCSV
        LectorImp <|-- LectorJSON
        LectorImp <|-- LectorXML

        enum TipoLector {
            MOCK, CSV, JSON, XML
        }

        class LectorFactory {
            +obtenerLector(tipo: TipoLector): Lector
        }
    }

    package export {
        interface Documento{
            +getContenido(): Map<String, Object[]>
            +getTitulo(): String
            +getPie(): String
        }

        Interface Exportable {
            +crearFichero(doc: Documento): byte[]
        }

        abstract DocumentoUtil {
            +{abstract}crearFichero(doc: Documento): byte[]
        }

        class ExcelUtil
        class WordUtil
        class PDFUtil
        class EscritorMock

        Exportable <|.. DocumentoUtil

        DocumentoUtil <|-- ExcelUtil
        DocumentoUtil <|-- WordUtil
        DocumentoUtil <|-- PDFUtil
        DocumentoUtil <|-- EscritorMock
        
        enum TipoDocumento {
            MOCK, EXCEL, DOCX, PDF
        }

        class ExportFactory {
            +obtenerExport(tipo: TipoDocumento): Escritor
        }
    }

    package printer {
        class Impresora {
            +imprimir(Imprimible): void
        }
        interface Imprimible {
            +obtenerDatos(producto: Producto): String
            +obtenerDatos(empleado: Empleado): String
        }
    }
}

package exception {
    class MercaDawException
    class LectorException
    class FormatoIncorrectoException
    class DAOException

    MercaDawException <|-- LectorException
    LectorException <|-- FormatoIncorrectoException
    MercaDawException <|-- DAOException

    '! A medida de codificación anyadir mas
}

Imprimible <|.. Sede

component org.apache.poi
org.apache.poi <.. DocumentoUtil

Documento <|.. Sede

@enduml