@startuml Entity
set namespaceSeparator none
allow_mixing

package es.tiernoparla.daw.mercadaw.model.entity {

    package producto {
        class ProductoFactory {
            +crear(categoria: CategoriaProducto): Producto
        }

        class Caracteristica {
            -altura: double
            -anchura: double
            -peso: double
            -numElementos: int

            +calcularRecargoPeso(): double
            +calcularRecargoAltura(): double
            +calcularRecargoAnchura(): double
            +calcularRecargoNumElementos(): double
        }

        abstract Producto {
            -nombre: String
            -marca: String
            -precio: double
            -descripcion: String

            +calcularPrecio(): double
        }

        Caracteristica "1" --*  "1" Producto

        class Alimentacion {
            +{static} CATEGORIA: CategoriaProducto = ALIMENTACION
            +{static} IVA: TipoIVA = SUPERREDUCIDO
        }

        class Drogueria {
            +{static} CATEGORIA: CategoriaProducto = DROGUERIA
            +{static} IVA: TipoIVA = REDUCIDO
        }

        class Cosmetica {
            +{static} CATEGORIA: CategoriaProducto = COSMETICA
            +{static} TipoIVA = GENERAL
        }

        Producto <|-- Alimentacion
        Producto <|-- Drogueria
        Producto <|-- Cosmetica
    }

    package persona {

        abstract Persona {
            #nombre: String
            #apellidos: String
        }

        package empleado {

            class EmpleadoFactory {
                +crear(categoria: CategoriaEmpleado): Empleado
            }

            class Empleado {
                +{static} CATEGORIA: CategoriaEmpleado = Empleado
                +{static} SUELDO = 1000
                #id: int
            }

            class Reponedor {
                +{static} CATEGORIA: CategoriaEmpleado = Reponedor
                +{static} SUELDO = 1200
            }

            class Cajero {
                +{static} CATEGORIA: CategoriaEmpleado = Cajero
                +{static} SUELDO = 1300
            }

            class Encargado {
                +{static} CATEGORIA: CategoriaEmpleado = Encargado
                +{static} SUELDO = 1500
            }

        }

        class Cliente {
            -codPostal: int
            -email: String
        }

        Empleado <|-- Reponedor
        Empleado <|-- Cajero
        Empleado <|-- Encargado

        Persona <|-- Empleado
        Persona <|-- Cliente
    }

}
Sede o-- Empleado
Sede o-- Producto

@enduml