@startuml Entity
set namespaceSeparator none
allow_mixing

package es.tiernoparla.daw.mercadaw.model.entity {

    package producto {
        class ProductoFactory {
            +obtenerProducto(categoria: CategoriaProducto): MercaDaw
        }

        abstract Producto {
            -nombre: String
            -marca: String
            -precio: double
            -altura: double
            -anchura: double
            -peso: double
            -numElementos: int
            -descripcion: String
            +calcularComision(): double
            +calcularRecargoPeso(): double
            +calcularRecargoAltura(): double
            +calcularRecargoAnchura(): double
            +calcularRecargoElementos(): double
            +{abstract}calcularIVA(): double
            +Producto(pb: ProductoBuilder)
            +{static} builder(): ProductoBuilder
        }

        class Alimentacion {
            +{static} CATEGORIA: CategoriaProducto = ALIMENTACION
            +{static} IVA= 4
        }

        class Drogueria {
            +{static} CATEGORIA: CategoriaProducto = DROGUERIA
            +{static} IVA= 10
        }

        class Cosmetica {
            +{static} CATEGORIA: CategoriaProducto = COSMETICA
            +{static} IVA= 21
        }

        class ProductoBuilder {
            -nombre: String
            -marca: String
            -precio: double
            -altura: double
            -anchura: double
            -peso: double
            -numElementos: int
            -descripcion: String
            +setNombre(nombre: String): ProductoBuilder
            +setMarca(marca: String): ProductoBuilder
            +setPrecio(precio: double): ProductoBuilder
            +setAltura(altura: double): ProductoBuilder
            +setAnchura(anchura: double): ProductoBuilder
            +setPeso(peso: double): ProductoBuilder
            +setNumElementos(numElementos: int): ProductoBuilder
            +setDescripcion(descripcion: String): ProductoBuilder
            ~ProductoBuilder()
            +build(): Producto
        }

        Producto <|-- Alimentacion
        Producto <|-- Drogueria
        Producto <|-- Cosmetica
    }

    package persona {

        class Empleado {
            +{static} CATEGORIA: CategoriaEmpleado = Empleado
            +{static} SUELDO = 1000
            #id: int
        }

        abstract Persona {
            #nombre: String
            #apellidos: String
        }

        class Reponedor {
            +{static} CATEGORIA: CategoriaEmpleado = Reponedor
            +{static} SUELDO = 1200
        }

        class Cajero {
            +{static} CATEGORIA: CategoriaEmpleado = Cajero
            +{static} SUELDO = 1300
        }

        class Encargado {
            +{static} CATEGORIA: CategoriaEmpleado = Encargado
            +{static} SUELDO = 1500
        }

        class Cliente {
            -codPostal: int
            -email: String
        }

        Empleado <|-- Reponedor
        Empleado <|-- Cajero
        Empleado <|-- Encargado

        Persona <|-- Empleado
        Persona <|-- Cliente
    }

}
Sede o-- Empleado
Sede o-- Producto

@enduml