@startuml Diagrama de Clases Borrar
skinparam BackgroundColor antiquewhite/black
allow_mixing
set namespaceSeparator none

package es.tiernoparla.daw.mercadaw{

    package util #White{

        package reader #Grey{

        }

        package export #TECHNOLOGY{

        }
    }

    package exception #White{

    }

    package model #White{

        interface Mercadaw #Violet{

        }

        class Empleado #LightGreen{

        }
    
        class CLiente #LightGreen{

        }

        package database #Yellow{

        }

        abstract Producto #LightSkyBlue{

        }

    }

    package view #White{

        enum Vista #Salmon{

        }

        abstract ViewController #LightSkyBlue{

        }
    }

    package controller #White{
        
        class MercadawController #LightGreen{

        }
    }

}

@enduml

@startuml Diagrama de Clases Modelo
allow_mixing
set namespaceSeparator none

package es.tiernoparla.daw.mercadaw.model #CadetBlue {
    interface MercadawDAO #Violet{
        + insertar(p: Producto) : int
        + insertar(e: Empleado) : int
        + insertar(productos: List<Producto>) : int
        + insertar(empleados: List<Empledo>) : int
        + actualizar(p: Producto) : int
        + actualizar(e: Empleado) : int
        + listarProductos() : List<Producto>
        + listarEmpleados() : List<Empleado>
    }

    abstract class Persona #LightSkyBlue {
        - nombre : String
        - apellido : String
    }

    class Empleado #LightGreen{
        + SUELDO : int = 1000 {static}
        - categoria : Categoria = Empleado
        - ID : int
    }

    class Cliente #LightGreen{

    }

    package database #LightGoldenRodYellow {
        
    }

    abstract Producto #LightSkyBlue{

    }
}

@enduml