@startuml CasosUso
left to right direction

actor Usuario as u

rectangle MercaDaw {
    usecase "Gestión de productos" as gp
    usecase "Gestión de empleados" as ge
    usecase "Gestión de compras" as gc
    usecase "Cargar los datos iniciales" as ci
    usecase "Dar de alta un producto" as dp
    usecase "Dar de alta un empleado" as de
    usecase "Visualizar los datos del producto" as vp
    usecase "Visualizar listado de empleados" as ve
    usecase "Dar de alta una compra" as dc
    usecase "Listar las compras" as lc
    usecase "Listar stock de los productos" as lp
    usecase "Obtener el precio de un producto" as pvp
    usecase "Imprimir una etiqueta para clasificar el producto" as ep
    usecase "Calcular las nóminas de los trabajadores" as ne
    usecase "Exportar datos" as ed
    usecase "Generar Excel" as excel
    usecase "Generar PDF" as pdf
}

u -- gp
u -- ge
u -- ci
u -- gc
u -- ed

gp <|-- dp
gp <|-- vp
gp <|-- lp
gp <|-- pvp
gp <|-- ep
ge <|-- de
ge <|-- ve
ge <|-- ne
gc <|-- dc
gc <|-- lc
ed <|-- excel
ed <|-- pdf

@enduml