CREATE OR REPLACE FUNCTION OBTENER_IDENTIFICADOR RETURN INTEGER IS
    v_identificador INTEGER;
BEGIN
    SELECT MAX(ID_COMPRA) INTO v_identificador 
    FROM COMPRA;

    RETURN v_identificador + 1;
END OBTENER_IDENTIFICADOR;
/


CREATE OR REPLACE PROCEDURE ALTA_COMPRA(v_ean IN PRODUCTOS.EAN%TYPE , v_stock IN PRODUCTO_SEDE.STOCK%TYPE, v_id_cliente IN CLIENTE.ID_CLIENTE%TYPE) IS
    v_identificador COMPRA.ID_COMPRA%TYPE;
BEGIN
    v_identificador := OBTENER_IDENTIFICADOR;

    INSERT INTO COMPRA (ID_COMPRA, FECHA_COMPRA, ID_CLIENTE)
    VALUES (v_identificador, TO_CHAR(SYSDATE, 'DD-MON-YYYY'), v_id_cliente);

    UPDATE PRODUCTO_SEDE
    SET STOCK = STOCK - v_stock
    WHERE EAN = v_ean;

END ALTA_COMPRA;
/


-- POR SI NECESITAS LAS TABLAS PARA TRABAJAR;

DROP TABLE COMPRA;
CREATE TABLE COMPRA (
                    ID_COMPRA NUMERIC,
                    FECHA_COMPRA DATE,
                    ID_CLIENTE INTEGER ,
                    PRIMARY KEY (ID_COMPRA),
                    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE));

DROP TABLE CLIENTE;
CREATE TABLE CLIENTE (
                    ID_CLIENTE NUMERIC PRIMARY KEY,
                    NOMBRE VARCHAR2(25) ,
                    APELLIDOS VARCHAR2(25),
                    COD_POSTAL NUMERIC(5));

DROP TABLE PRODUCTO_SEDE;
CREATE TABLE PRODUCTO_SEDE (
                    EAN NUMERIC,
                    UBICACION VARCHAR2(25),
                    STOCK NUMERIC,
                    PRIMARY KEY (EAN, UBICACION),
                    FOREIGN KEY (EAN) REFERENCES PRODUCTOS(EAN),
                    FOREIGN KEY (UBICACION) REFERENCES SEDE(UBICACION));

DROP TABLE SEDE;
CREATE TABLE SEDE (
                    UBICACION VARCHAR2(25) PRIMARY KEY);

DROP TABLE PRODUCTOS;
CREATE TABLE PRODUCTOS (
                    EAN NUMERIC PRIMARY KEY,
                    NOMBRE VARCHAR2(50),
                    MARCA VARCHAR2(25),
                    PRECIO NUMBER(5,2),
                    ALTURA NUMBER(5,2),  
                    ANCHURA NUMBER(5,2),
                    PESO NUMBER(5,2),
                    NUM_ELEMENTOS NUMERIC,
                    DESCRIPCION VARCHAR2(100),
                    CATEGORIA VARCHAR2(25),
                    CHECK (CATEGORIA IN ('Alimentacion', 'Drogueria', 'Cosmetica')));


INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, APELLIDOS, COD_POSTAL) VALUES (1, 'Juan', 'García', 28001);
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, APELLIDOS, COD_POSTAL) VALUES (2, 'María', 'López', 28002);
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, APELLIDOS, COD_POSTAL) VALUES (3, 'Pedro', 'Martínez', 28003);
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, APELLIDOS, COD_POSTAL) VALUES (4, 'Ana', 'Sánchez', 28004);
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, APELLIDOS, COD_POSTAL) VALUES (5, 'Miguel', 'González', 28005);
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, APELLIDOS, COD_POSTAL) VALUES (6, 'Laura', 'Rodríguez', 28006);

INSERT INTO PRODUCTOS (EAN, NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION, CATEGORIA) VALUES
(1, 'Leche Entera', 'Puleva', 1.20, 20.00, 10.00, 1.00, 1, 'Leche de vaca entera en brik', 'Alimentacion');
INSERT INTO PRODUCTOS (EAN, NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION, CATEGORIA) VALUES
(2, 'Galletas Maria', 'Fontaneda', 1.50, 15.00, 5.00, 0.30, 1, 'Galletas clásicas', 'Alimentacion');
INSERT INTO PRODUCTOS (EAN, NOMBRE, MARCA, PRECIO, ALTURA, ANCHURA, PESO, NUM_ELEMENTOS, DESCRIPCION, CATEGORIA) VALUES
(3, 'Papel Higiénico', 'Scottex', 3.90, 10.00, 10.00, 0.20, 6, 'Papel higiénico suave', 'Drogueria');


INSERT INTO SEDE (UBICACION) VALUES ('Madrid');

INSERT INTO PRODUCTO_SEDE (EAN, UBICACION, STOCK) VALUES (1, 'Madrid', 96);
INSERT INTO PRODUCTO_SEDE (EAN, UBICACION, STOCK) VALUES (2, 'Madrid', 40);
INSERT INTO PRODUCTO_SEDE (EAN, UBICACION, STOCK) VALUES (3, 'Madrid', 60);



INSERT INTO COMPRA (ID_COMPRA, FECHA_COMPRA, ID_CLIENTE) VALUES (1, SYSDATE, 1);
INSERT INTO COMPRA (ID_COMPRA, FECHA_COMPRA, ID_CLIENTE) VALUES (2, SYSDATE, 2);
INSERT INTO COMPRA (ID_COMPRA, FECHA_COMPRA, ID_CLIENTE) VALUES (3, SYSDATE, 3);
INSERT INTO COMPRA (ID_COMPRA, FECHA_COMPRA, ID_CLIENTE) VALUES (4, SYSDATE, 4);